Fixes many bugs having to do with assuming paths exist; if an output path does not exist, then these scripts now creates these paths

diff --git a/scripts/makeAnyMovie b/scripts/makeAnyMovie
--- a/scripts/makeAnyMovie
+++ b/scripts/makeAnyMovie
@@ -17,7 +17,7 @@ endif
 if (!(-e $WORKFLOW_IMG_ROOT)) then
     mkdir $WORKFLOW_IMG_ROOT
     if ($?) then 
-        echo ERROR making image root directory $WORKFLOW_IMG_ROOT
+        echo "[ makeAnyMovie ] ERROR making image root directory $WORKFLOW_IMG_ROOT"
         exit 1
     endif
 endif
@@ -27,12 +27,12 @@ set TIME_CONVERT = "${DRMS_BINS_INSTALL_DIR}"/time_convert
 @ min15 = 60 * 15
 if ($#argv > 0) then # get start time
   set want = $1
-  set want_t = `TIME_CONVERT time=$want`
+  set want_t = `$TIME_CONVERT time=$want`
   @ startimg = $want_t / $min15
   shift
 else
   set now = `date -u +%Y.%m.%d_%H:%M:%S`
-  set now_t = `TIME_CONVERT time=$now`
+  set now_t = `$TIME_CONVERT time=$now`
   @ nowimg = $now_t / $min15
   @ day2 = 48 * 4
   @ startimg = $nowimg - $day2
@@ -41,12 +41,12 @@ endif
 
 if ($#argv > 0) then # get end time
   set want = $1
-  set want_t = `TIME_CONVERT time=$want`
+  set want_t = `$TIME_CONVERT time=$want`
   @ endimg = $want_t / $min15
   shift
 else
   set now = `date -u +%Y.%m.%d_%H:%M:%S`
-  set now_t = `TIME_CONVERT time=$now`
+  set now_t = `$TIME_CONVERT time=$now`
   @ endimg = $now_t / $min15
 endif
 @ endtime_t = $endimg * $min15
@@ -105,97 +105,122 @@ set images_dir = $WORKFLOW_IMG_ROOT/images
 if (!(-e $images_dir)) then
     mkdir $images_dir
     if ($?) then 
-        echo ERROR making images root directory $images_dir
+        echo "[ makeAnyMovie ] ERROR making images directory $images_dir"
         exit 1
     endif
 endif
 
 set movies_dir = $WORKFLOW_IMG_ROOT/movies
-
 if (!(-e $movies_dir)) then
     mkdir $movies_dir
     if ($?) then 
-        echo ERROR making movies root directory $movies_dir
+        echo "[ makeAnyMovie ] ERROR making movies directory $movies_dir"
         exit 1
     endif
 endif
 
-set WORK = $movies_dir/$Quant'_movies'.$$
+set special_dir = $movies_dir/special
+if (!(-e $special_dir)) then
+    mkdir $special_dir
+    if ($?) then 
+        echo "[ makeAnyMovie ] ERROR making special directory $special_dir"
+        exit 1
+    endif
+endif
 
-mkdir $WORK
-mkdir $WORK/frames
+set work_dir = $movies_dir/$Quant'_movies'.$$
+if (!(-e $work_dir)) then
+    mkdir $work_dir
+    if ($?) then 
+        echo "[ makeAnyMovie ] ERROR making work directory $work_dir"
+        exit 1
+    endif
+endif
+
+set frames_dir = $work_dir/frames
+
+if (!(-e $frames_dir)) then
+    mkdir $frames_dir
+    if ($?) then 
+        echo "[ makeAnyMovie ] ERROR making frames directory $frames_dir"
+        exit 1
+    endif
+endif
 
 @ imgtime_t = $starttime_t 
 set i = 0
 while ($imgtime_t <= $endtime_t)
-  set imgtime = `TIME_CONVERT s=$imgtime_t zone=TAI`
-  set yyyymmdd = `echo $imgtime | sed -e 's/_.*//' -e 's/\./Q/' -e 's/\./X/'`
-  set YEAR = `echo $yyyymmdd | sed -e 's/Q.*//'`
-  set MON = `echo $yyyymmdd | sed -e 's/^.*Q//' -e 's/X.*//'`
-  set DAY = `echo $yyyymmdd | sed -e 's/^.*X//'`
-  set yyyymmdd = $YEAR$MON$DAY
-  set hhmmss = `echo $imgtime | sed -e 's/_/Q/' -e 's/.*Q//' -e 's/://g' -e 's/_TAI//'`
-  set I = `printf "%04d" $i`
-  set filename = $yyyymmdd'_'$hhmmss'_'$Quant'_'$Size'.'$Type
-  if ($i == 0) set Startname = $yyyymmdd'_'$hhmmss
-  set Endname = $yyyymmdd'_'$hhmmss
-  set Imgpath = $images_dir/$YEAR/$MON/$DAY
-  set targpath = $WORK/frames
-  set Image = $Imgpath/$filename
-  if (-e $Image) then
-    set FileSize=`stat --format="%s" $Image`
-    if ($FileSize < $minFileSize) then
-       echo Blank image detected for $Image
+    set imgtime = `$TIME_CONVERT s=$imgtime_t zone=TAI`
+    set yyyymmdd = `echo $imgtime | sed -e 's/_.*//' -e 's/\./Q/' -e 's/\./X/'`
+    set YEAR = `echo $yyyymmdd | sed -e 's/Q.*//'`
+    set MON = `echo $yyyymmdd | sed -e 's/^.*Q//' -e 's/X.*//'`
+    set DAY = `echo $yyyymmdd | sed -e 's/^.*X//'`
+    set yyyymmdd = $YEAR$MON$DAY
+    set hhmmss = `echo $imgtime | sed -e 's/_/Q/' -e 's/.*Q//' -e 's/://g' -e 's/_TAI//'`
+    set I = `printf "%04d" $i`
+    set filename = $yyyymmdd'_'$hhmmss'_'$Quant'_'$Size'.'$Type
+
+    if ($i == 0) set Startname = $yyyymmdd'_'$hhmmss
+
+    set Endname = $yyyymmdd'_'$hhmmss
+    set Imgpath = $images_dir/$YEAR/$MON/$DAY
+    set targpath = $frames_dir
+    set Image = $Imgpath/$filename
+
+    if (-e $Image) then
+        set FileSize=`stat --format="%s" $Image`
+        if ($FileSize < $minFileSize) then
+            echo Blank image detected for $Image
+        else
+            ln -s $Image $targpath/$I.$Type
+            @ i = $i + 1
+        endif
     else
-       ln -s $Image $targpath/$I.$Type
-       @ i = $i + 1
-    endif
-  else
-    echo no frame found for $Image
-  endif
-  @ imgtime_t = $imgtime_t + $cadence
-end
+        echo no frame found for $Image
+        endif
+        @ imgtime_t = $imgtime_t + $cadence
+    end
 
 set HERE = $cwd
 
-cd $WORK/frames
+cd $frames_dir
 
 echo Movie making place is $cwd
-echo $WORK
+echo $work_dir
 
- set echo
+set echo
 
 @ mins = $cadence / 60
 
-cd $WORK/frames
 if ( $JSOC_MACHINE == 'linux_avx' ) then
-  set mpg_opts = "-b:v 35000k"
-  set mp4_opts = "-b:v 35000k"
-#  set mpg_opts = "-qscale 5 -r 20 -b:v 9600"
-#  set mp4_opts = "-qscale 5 -r 20 -b 9600 -c mpeg4"
+    set mpg_opts = "-b:v 35000k"
+    set mp4_opts = "-b:v 35000k"
 else
-  set mpg_opts = "-qscale 5 -r 20 -b 9600"
-  set mp4_opts = "-qscale 5 -r 20 -b 9600"
+    set mpg_opts = "-qscale 5 -r 20 -b 9600"
+    set mp4_opts = "-qscale 5 -r 20 -b 9600"
 endif
 
 if ($path_given == 0) then
-  set MOVIE = $WORK/$Quant'_'$Size'_'$Startname'-'$Endname'_'$mins'm'
+    set MOVIE = $work_dir/$Quant'_'$Size'_'$Startname'-'$Endname'_'$mins'm'
 
-#  ffmpeg -qscale 5 -r 20 -b 9600 -i %04d.$Type $MOVIE.mpg 
-  ffmpeg $mpg_opts -i %04d.$Type $MOVIE.mpg
-  if ($status == 0) then
-      mv $MOVIE.mpg $movies_dir/special
-  endif
+    #  ffmpeg -qscale 5 -r 20 -b 9600 -i %04d.$Type $MOVIE.mpg 
+    ffmpeg $mpg_opts -i %04d.$Type $MOVIE.mpg
 
-#  ffmpeg -qscale 5 -r 20 -b 9600 -i %04d.$Type $MOVIE.mp4 
-  ffmpeg -i %04d.$Type $mp4_opts $MOVIE.mp4
-  if ($status == 0) then
-      mv $MOVIE.mp4 $movies_dir/special
-  endif
-else
-#  ffmpeg -qscale 5 -r 20 -b 9600 -i %04d.$Type $specified_path
-  ffmpeg -i %04d.$Type $mp4_opts $specified_path
-endif
+    if ($status == 0) then
+        mv $MOVIE.mpg $special_dir
+    endif
 
-rm -rf $WORK
+    #  ffmpeg -qscale 5 -r 20 -b 9600 -i %04d.$Type $MOVIE.mp4 
+    ffmpeg -i %04d.$Type $mp4_opts $MOVIE.mp4
+
+    if ($status == 0) then
+        mv $MOVIE.mp4 $special_dir
+    endif
+
+    else
+        #  ffmpeg -qscale 5 -r 20 -b 9600 -i %04d.$Type $specified_path
+        ffmpeg -i %04d.$Type $mp4_opts $specified_path
+    endif
+
+rm -rf $work_dir
 cd $HERE
diff --git a/scripts/makeIcmovie b/scripts/makeIcmovie
--- a/scripts/makeIcmovie
+++ b/scripts/makeIcmovie
@@ -13,7 +13,7 @@ endif
 if (!(-e $WORKFLOW_IMG_ROOT)) then
     mkdir $WORKFLOW_IMG_ROOT
     if ($?) then 
-        echo ERROR making image root directory $WORKFLOW_IMG_ROOT
+        echo "[ makeIcmovie ] ERROR making image root directory $WORKFLOW_IMG_ROOT"
         exit 1
     endif
 endif
@@ -41,7 +41,7 @@ set images_dir = $WORKFLOW_IMG_ROOT/images
 if (!(-e $images_dir)) then
     mkdir $images_dir
     if ($?) then 
-        echo ERROR making images root directory $images_dir
+        echo "[ makeIcmovie ] ERROR making images directory $images_dir"
         exit 1
     endif
 endif
@@ -50,16 +50,48 @@ set movies_dir = $WORKFLOW_IMG_ROOT/movies
 if (!(-e $movies_dir)) then
     mkdir $movies_dir
     if ($?) then 
-        echo ERROR making movies root directory $movies_dir
+        echo "[ makeIcmovie ] ERROR making movies directory $movies_dir"
+        exit 1
+    endif
+endif
+
+set latest_movies_dir = $movies_dir/latest
+if (!(-e $latest_movies_dir)) then
+    mkdir $latest_movies_dir
+    if ($?) then 
+        echo "[ makeIcmovie ] ERROR making latest movies directory $latest_movies_dir"
+        exit 1
+    endif
+endif
+
+set d14d_movies = $movies_dir/.14dmovies
+if (!(-e $d14d_movies)) then
+    mkdir $d14d_movies
+    if ($?) then 
+        echo "[ makeIcmovie ] ERROR making d14d movies directory $d14d_movies"
         exit 1
     endif
 endif
 
 foreach Quant (Ic_flat M M_color)
-    set THISWORK = $Quant'_movies'.$$
-    set WORK = $movies_dir/$THISWORK
-    mkdir $WORK
-    mkdir $WORK/frames
+    set work_dir = $movies_dir/$Quant'_movies'.$$
+
+    if (!(-e $work_dir)) then
+        mkdir $work_dir
+        if ($?) then 
+            echo "[ makeIcmovie ] ERROR making work directory $work_dir"
+            exit 1
+        endif
+    endif
+
+    set frames_dir = $work_dir/frames
+    if (!(-e $frames_dir)) then
+        mkdir $frames_dir
+        if ($?) then 
+            echo "[ makeIcmovie ] ERROR making frames directory $frames_dir"
+            exit 1
+        endif
+    endif
 
     # First make 2 days at 15 minutes
     @ imgtime_t = $endtime_t - 172800
@@ -77,7 +109,7 @@ foreach Quant (Ic_flat M M_color)
         set I = `printf "%04d" $i`
         set filename = $yyyymmdd'_'$hhmmss'_'$Quant'_'$Size'.'$Type
         set Imgpath = $images_dir/$YEAR/$MON/$DAY
-        set targpath = $WORK/frames
+        set targpath = $frames_dir
         set Image = $Imgpath/$filename
 
         if (-e $Image) then
@@ -95,9 +127,8 @@ foreach Quant (Ic_flat M M_color)
         @ imgtime_t = $imgtime_t + $cadence
     end
 
-    set HERE = $WORKFLOW_IMG_ROOT/movies/
-    ls -ld $WORK/frames
-    cd $WORK/frames
+    ls -ld $frames_dir
+    cd $frames_dir
 
     echo Movie making place is $cwd
 
@@ -110,48 +141,55 @@ foreach Quant (Ic_flat M M_color)
         set mp4_opts = "-qscale 5 -r 20 -b 9600"
     endif
 
-    set MOVIE = $WORK/$Quant'_2d'.mpg
+    set MOVIE = $work_dir/$Quant'_2d'.mpg
     #  ffmpeg -qscale 5 -r 20 -b 9600 -i %04d.$Type $MOVIE 
     ffmpeg -i %04d.$Type $mpg_opts $MOVIE
 
+    # the cp commands use $Imgpath, which is not defined in this scope; it 
+    # was defined in the above while loop, and it takes on a different value
+    # during each iteration; the value used here will be either the last value
+    # of the iteration, or I guess the empty string if the while loop above
+    # never executed - THIS IS A BUG
+    set image_dir = $Imgpath
+    if (!(-e $image_dir)) then
+        mkdir $image_dir
+        if ($?) then 
+            echo "[ makeIcmovie ] ERROR making image directory $image_dir"
+            exit 1
+        endif
+    endif
+
     if ($status == 0) then
         cp $MOVIE $Imgpath
-        mv $MOVIE $WORKFLOW_IMG_ROOT/movies/latest
+        mv $MOVIE $latest_movies_dir
     endif
   
-    set MOVIE = $WORK/$Quant'_2d'.mp4
+    set MOVIE = $work_dir/$Quant'_2d'.mp4
     #  ffmpeg -qscale 5 -r 20 -b 9600 -i %04d.$Type $MOVIE
     ffmpeg -i %04d.$Type $mp4_opts $MOVIE
 
     if ($status == 0) then
         cp $MOVIE $Imgpath
-        mv $MOVIE $WORKFLOW_IMG_ROOT/movies/latest
+        mv $MOVIE $latest_movies_dir
     endif
 
     cd $movies_dir
-    set D14dMOVIES = .14dmovies
-    if (!(-e $D14dMOVIES)) mkdir $D14dMOVIES
 
     # on even hour endtime, make longer movie also
     @ nowtime_t = $endtime_t / 3600
     @ nowhour_t = $nowtime_t * 3600
     if ($nowhour_t == $endtime_t) then
-        set THISWORK = $Quant'_movies'.$$
-        set WORK = $movies_dir/$THISWORK
-        mkdir $WORK
-        mkdir $WORK/frames
-        cd $WORK/frames
+        cd $frames_dir
         @ fourteen = 86400 * 14
         @ nowtime_t = $endtime_t - $fourteen
         set nowtime = `$TIME_CONVERT zone=TAI s=$nowtime_t`
         set endtime = `$TIME_CONVERT zone=TAI s=$endtime_t`
-        "${DRMS_SCRS_INSTALL_DIR}"/makeAnyMovie $nowtime $endtime 15 $Quant 1k ""$HERE/$D14dMOVIES/$Quant"_14d.mp4"
+        "${DRMS_SCRS_INSTALL_DIR}"/makeAnyMovie $nowtime $endtime 15 $Quant 1k ""$d14d_movies/$Quant"_14d.mp4"
     endif
 end
 
-cd $WORKFLOW_IMG_ROOT/movies
-ls -l $D14dMOVIES/
-mv $D14dMOVIES/Ic_flat_14d.mp4 $D14dMOVIES/M_14d.mp4 $WORKFLOW_IMG_ROOT/movies/latest/
-mv $D14dMOVIES/M_color_14d.mp4 $WORKFLOW_IMG_ROOT/movies/latest/
-rm -rf $D14dMOVIES
-rm -rf $WORKFLOW_IMG_ROOT/movies/*.$$
+ls -l $d14d_movies/
+mv $d14d_movies/Ic_flat_14d.mp4 $d14d_movies/M_14d.mp4 $latest_movies_dir/
+mv $d14d_movies/M_color_14d.mp4 $latest_movies_dir/
+rm -rf $d14d_movies
+rm -rf $movies_dir/*.$$
